## Database Configuration
#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/ecampus
#    username: postgres
#    password: toor
#    driver-class-name: org.postgresql.Driver
#
#  # JPA/Hibernate
#  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    hibernate:
#      ddl-auto: validate
#    properties:
#      hibernate:
#        format_sql: true
#    show-sql: true
#
#  # Liquibase
#  liquibase:
#    change-log: classpath:db/changelog/db.changelog-master.yaml
#    enabled: true
#
## Server Configuration
#server:
#  port: 8080
#  servlet:
#    context-path: /api
#
## Application-specific properties
#app:
#  jwt:
#    secret: your-secret-key-should-be-at-least-256-bits-long-and-very-secure
#    expiration-ms: 86400000  # 24 hours
#
#
#cloudinary:
#  cloud-name: hnaiuwzhz
#  api-key: 658681139138473
#  api-secret: TCg782vyTKmBXOA6tNRlbCsq0jY